apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: example-cluster-ig
    networking.gke.io/managed-certificates: ssl-sample-certificate
