apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - certificate.yaml
patchesStrategicMerge:
  - ingress.yaml
images:
  - name: helloworld
    newName: gcr.io/[PROJECT_ID]/helloworld
    newTag: latest
