apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: google-managed-ssl-example-app
spec:
  ports:
  - name: app-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: google-managed-ssl-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: helloworld
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 10Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: google-managed-ssl-example-app
spec:
  backend:
    serviceName: google-managed-ssl-example-app
    servicePort: app-port
